language: node_js
node_js:
  - '8'

script: npm i -g hexo && npm i && hexo g

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  skip_cleanup: true
  on:
    branch: master
  repo: Snakeflute/Snakeflute.github.io # your github pages repo name
  target_branch: master 